### ISSUE TITLE
Contributing guide is missing

### ISSUE THREAD

**Issue by HasanAliKaraca** [aspnet/Docs.tr-tr#4]
If not, link is broken 

https://github.com/aspnet/Docs.tr-tr/blob/live/CONTRIBUTING.md

**Comment by CeciAc** [comment]
Hello, @HasanAliKaraca,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@JasonCard can you please check this issue?
It looks like it's fixed but not active for all locales

**Comment by JasonCard** [comment]
@HasanAliKaraca Thank you for reporting this issue.
CONTRIBUTING.md was missing for Turkish, Czech, and Polish, so it's currently being localized with machine translation.
I'll update then it's localized.
cc @CeciAc

**Comment by JasonCard** [comment]
@HasanAliKaraca CONTRIBUTING.md is now localized in machine translation. 
Thank you again for your contribution.

Kind regards,
Microsoft DOCS International Team
