### ISSUE TITLE
bad example

### ISSUE THREAD

**Issue by skaradogan189** [aspnet/Docs.tr-tr#9]
[Geri bildiriminizi buraya girin]
örneğin türkçesi çok bozuk oluşturulan itemların adı belirsiz

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Öğretici: ASP.NET Core MVC ile bir web API'si oluşturma](https://docs.microsoft.com/tr-tr/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs.tr-tr/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Merhaba @skaradogan189 
Yorumunuzu takdir ediyor ve docs.microsoft.com deneyiminizi geliştirmeye çalışıyoruz. Öte yandan, geri bildiriminizle ilgilenmek için daha fazla bilgiye ihtiyacımız var. Lütfen daha ayrıntılı bilgi sağlayın ve yorumunuzu netleştirin.
Saygılarımızla,
Microsoft DOCS Uluslararası Ekibi

**Comment by CeciAc** [comment]
Merhaba @anurse 
Önceki açıklamamızı takip ediyoruz. Geri bildiriminizle ilgilenmek için daha fazla bilgiye ihtiyacımız var. Lütfen daha ayrıntılı bilgi sağlayın ve yorumunuzu netleştirin.
Saygılarımızla,
Microsoft DOCS Uluslararası Ekibi

**Comment by CeciAc** [comment]
Merhaba @skaradogan189 
Yorumunuz için tekrar teşekkürler.
Ne yazık ki hala eksik bilgileri alamadık ve geri bildiriminizle ilgili işlem yapamıyoruz. Şu anda bu GitHub sorununu kapatıyoruz ama gelecekte daha fazla geri bildirim göndermenizi öneririz.
Saygılarımızla,
Microsoft DOCS Uluslararası Ekibi
